/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Before You Invest',
      items: [
        'before-you-invest/understanding-cash-flow',
        'before-you-invest/goal-setting',
        'before-you-invest/budgeting',
        'before-you-invest/insurance',
        'before-you-invest/debt',
      ],
    },
    {
      type: 'category',
      label: 'What to Invest in',
      items: [
        'what-to-invest-in/types-of-assets',
        'what-to-invest-in/cash',
        'what-to-invest-in/non-productive-assets',
        'what-to-invest-in/real-estate',
        'what-to-invest-in/productive-assets',
      ],
    },
    {
      type: 'category',
      label: 'Securities Investment',
      items: [
        'securities-invement/value-investing',
        'securities-invement/passiveinvestor',
      ],
    },
    {
      type: 'category',
      label: 'Business Analysis & Valuation',
      items: [
        'business-analysis-and-valuation/business-analysis',
      ],
    },
  ],
};

export default sidebars;
